# Generated by Django 3.2.12 on 2022-11-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officeuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=200)),
                ('Epic', models.CharField(max_length=200)),
                ('Role_Name', models.TextField()),
                ('what', models.TextField()),
                ('why', models.TextField()),
                ('Table_name', models.CharField(max_length=500)),
                ('Table_Purpose', models.TextField()),
                ('Table_CRUD', models.CharField(max_length=500)),
            ],
        ),
    ]
