# Generated by Django 3.2.12 on 2022-11-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
