# Generated by Django 3.2.12 on 2022-11-23 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.officeuse')),
            ],
        ),
    ]
