# Generated by Django 3.2.12 on 2022-11-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Projects',
            new_name='Projects_name',
        ),
    ]
