# Generated by Django 3.2.12 on 2022-11-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_project_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
