# Generated by Django 3.2.12 on 2022-11-25 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='officeuse',
            name='Projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.pro'),
        ),
    ]
