# Generated by Django 3.2.12 on 2022-11-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20221125_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeuse',
            name='Projects',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='pro',
        ),
    ]
