# Generated by Django 3.2.12 on 2022-12-16 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20221216_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory_table1',
            name='Table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.table'),
        ),
    ]
