# Generated by Django 3.2.12 on 2022-12-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_header'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Header',
            new_name='userstorytable',
        ),
    ]
