# Generated by Django 3.2.12 on 2022-12-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_rename_header_userstorytable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStory_Table1',
        ),
    ]
