# Generated by Django 3.2.12 on 2022-12-21 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_delete_userstory_table1'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.project'),
            preserve_default=False,
        ),
    ]
