# Generated by Django 3.2.12 on 2023-01-09 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_auto_20230105_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='userstoryrole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.project')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.role')),
                ('User_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user_story')),
            ],
        ),
        migrations.CreateModel(
            name='userstoryepic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.epic')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.project')),
                ('User_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user_story')),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Portal', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('website', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('Application', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.project')),
                ('User_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user_story')),
            ],
        ),
    ]
