# Generated by Django 3.2.12 on 2023-01-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_device_userstoryepic_userstoryrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Application',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
