# Generated by Django 3.2.12 on 2023-01-19 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_alter_device_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='userstoryepic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.userstoryepic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='userstoryrole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.userstoryrole'),
            preserve_default=False,
        ),
    ]
