# Generated by Django 3.2.12 on 2023-01-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_auto_20230123_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Application',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='Portal',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='website',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
