# Generated by Django 3.2.12 on 2023-01-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_auto_20230123_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Application',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='Portal',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='website',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
